version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_AUTH0_DOMAIN=https://dev-dxya2auaytwzj1s4.us.auth0.com
        - VITE_AUTH0_CLIENT_ID=5wK2RTUV7YjnuFWbzMitk53eRx4Zbg6Y
        - VITE_AUTH0_AUDIENCE=https://snipet-searcher.com
        - VITE_API_URL=http://localhost:8082
    ports:
      - "3000:80"
    environment:
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8082
      - AUTH0_USERNAME=pit@mail.com
      - AUTH0_PASSWORD=Boca123!
      - VITE_AUTH0_DOMAIN=https://dev-dxya2auaytwzj1s4.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=5wK2RTUV7YjnuFWbzMitk53eRx4Zbg6Y
      - VITE_AUTH0_AUDIENCE=https://snipet-searcher.com
      - VITE_API_URL=http://localhost:8082
    restart: unless-stopped
